//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolAndStudent
    {
        public short StudntID { get; set; }
        public short SchoolID { get; set; }
        public string StudiesInID { get; set; }
    
        public virtual School School { get; set; }
        public virtual Student Student { get; set; }
    }
}
